@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json

### 1. FOXA1 gene expression
POST http://{{host}}/ai
Content-Type: {{contentType}}

{
    "query": "Give me the 10 samples with the highest FOXA1 gene expression."
}



### 2. Hillock cells TRIM24 gene expression
POST http://{{host}}/ai
Content-Type: {{contentType}}

{
    "query": "I want the data for cells that have ANNOTATION Hillock (normal) and their respective gene expression for the TRIM24 gene."
}


